---
- name: "Install Arch Linux from an Arch ISO"
  hosts: localhost
  vars_files:
      - var.yml
  tasks:
      - name: "Check internet connectivity"
        wait_for:
            host: archlinux.org
            port: 80

      - name: "Enable ntp"
        command: /usr/bin/timedatectl set-ntp true

      - name: "partitioning"
        include: partition.yml

      - name: "filesystem"
        include: filesystem.yml

      - name: "mount"
        include: mount.yml

      - name: "Installs base system using pacstrap"
        command: /usr/bin/pacstrap /mnt base base-devel ansible networkmanager vim

      - name: "Populates base system fstab with configured storage devices"
        shell: /usr/bin/genfstab -U -p /mnt >> /mnt/etc/fstab
