partition:
  name: /dev/sda
  volumes:
      boot:
           size: '550MiB'
           type: 'fat32'
           mount: '/mnt/boot' 
      root:
           type: 'ext4'
           mount: '/mnt'

user:
    name: "your_username"

locale:
    timezone: "Europe/Paris"
    languages:
        - "en_US.UTF-8"
