- name: "Create a ext4 filesystem on /dev/sda1 for boot"
  filesystem:
      fstype: ext4
      dev: /dev/sda1
      opts: -cc

- name: "Create a swap filesystem on /dev/sda2 for swap"
  filesystem:
      fstype: swap
      dev: /dev/sda2
      opts: -cc

- name: "Create a ext4 filesystem on /dev/sda3 for root"
  filesystem:
      fstype: ext4
      dev: /dev/sda3
      opts: -cc

- name: "Create a ext4 filesystem on /dev/sda4 for home"
  filesystem:
      fstype: ext4
      dev: /dev/sda4
      opts: -cc

- name: "Setup swap partition"
  shell: "mkswap /dev/sda2 && /usr/bin/swapon /dev/sda2"
