- name: "Create a ext4 filesystem on /dev/sda1 for boot"
  filesystem:
      fstype: ext4
      dev: /dev/sda1
      opts: -cc

- name: "Create a ext4 filesystem on /dev/sda3 for root"
  filesystem:
      fstype: ext4
      dev: /dev/sda2
      opts: -cc
