- name: "Create a ext4 filesystem on /dev/sda1 for boot"
  filesystem:
      fstype: ext4
      dev: /dev/sda1
      opts: -cc

# - name: "Setup swap partition"
#   shell: "mkswap /dev/sda2 && /usr/bin/swapon /dev/sda2"

- name: "Create a ext4 filesystem on /dev/sda3 for root"
  filesystem:
      fstype: ext4
      dev: /dev/sda2
      opts: -cc
