---
- name: Ensure a locale exists
  locale_gen:
      name: "{{ item }}"
      state: present
  with_items: "{{ locale.languages }}"

- name: Set timezone
  timezone:
      name: "{{ locale.timezone }}"

- name: set default locale
  command: localectl set-locale "LANG={{ item }}" #"LC_ALL={{ item }}"
  with_items: "{{ locale.languages }}"
