---
- name: "Install Arch Linux from an Arch ISO"
  hosts: localhost
  vars_files:
      - ../config.yml
  tasks:
      - name: "Check internet connectivity"
        wait_for:
            host: archlinux.org
            port: 80

      - name: "Enable ntp"
        command: timedatectl set-ntp true

      - name: "partitioning"
        include: partition.yml

      - name: "filesystem"
        include: filesystem.yml

      - name: "mount"
        include: mount.yml

      - name: "Installs base system using pacstrap"
        command: pacstrap /mnt base base-devel linux linux-firmware ansible vim

      - name: "Populates base system fstab with configured storage devices"
        shell: genfstab -U -p /mnt >> /mnt/etc/fstab
