---
- hosts: localhost
  vars_files: '../config.yml'
  vars_prompt:
      - name: root_password
        prompt: "What will be root password ?"
        private: yes 
        encrypt: "sha512_crypt"
        confirm: yes
        salt_size: 7

      - name: user_password
        prompt: "What will be for {{ user.name }} password ?"
        private: yes 
        encrypt: "sha512_crypt"
        confirm: yes
        salt_size: 7

  tasks:
      - name: Install networkmanager
        pacman:
            name: networkmanager
            state: present

      - name: Make sure networkmanager will be running after reboot
        systemd:
            name: NetworkManager
            enabled: yes
            state: started

      - include: locale.yml
      - include: users.yml
      - include: boot.yml
