---
- hosts: localhost
  vars_files: '../config.yml'
  vars_prompt:
      - name: password
        prompt: "What is your password?"
        private: yes 
  tasks:
      - name: Install networkmanager
        pacman:
            name: networkmanager
            state: present

      - name: Make sure networkmanager is running
        systemd:
            state: started
            name: NetworkManager

      - include: locale.yml
      - include: users.yml
      - include: boot.yml
